[workspace]
resolver = "2"
members = ["app/src-tauri", "cli", "core"]

[workspace.dependencies]
ab_glyph = "0.2"
base64 = "0.22"
bracket-color = "0.8"
clap = "4.5"
image = "0.25"
imageproc = "0.25"
object-detection-core = { path = "core"}
once_cell = "1.19"
serde = "1"
serde_json = "1"
tauri = "2.0.0-beta"
tauri-build = "2.0.0-beta"
tauri-plugin-dialog = "2.0.0-beta"
tauri-plugin-shell = "2.0.0-beta"
tract-onnx = "0.21"

[profile.release]
panic = "abort" # Strip expensive panic clean-up logic
codegen-units = 1 # Compile crates one after another so the compiler can optimize better
lto = true # Enables link to optimizations
opt-level = "s" # Optimize for binary size
strip = true # Remove debug symbols
